
runtime: nodejs10

env_variables:
  GCLOUD_STORAGE_BUCKET_FOOD: foodie-cibus-bucket-1
  GCLOUD_STORAGE_BUCKET_PROFILE: foodie-cibus-bucket-2

  SQL_USER: root
  SQL_PASSWORD: 4c3Bccus7mwP4ei0
  SQL_DATABASE: cibus_1
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: foodie-cibus-2020:us-west2:cibus

